### PR TITLE
add dotfiles for "Bash on Windows" / Windows Subsystem for Linux (WSL)

### PR DESCRIPTION
**Pull request by jieverson**
Windows 10 can now officially run native Ubuntu subsystem. Its default settings comes with Bash, but it's possible to install different shells (my settings are using Zsh).

### CODE REVIEW

**Comment by jieverson** [comment]
There is a broken link: (homesick article - http://technicalpickles.com/posts/never-leave-your-dotfiles-behind-again-with-homesick/)

Should I remove it?

**Comment by strugee** [comment]
@jieverson probably, in a second PR

**Comment by jieverson** [comment]
broken link to homesick article removed.

**Comment by webpro** [comment]
Thanks, @jieverson. The link shouldn't be removed, but fixed instead: http://technicalpickles.com/posts/never-leave-your-dotfiles-behind-again-with-homesick (just remove the trailing slash).

**Comment by jieverson** [comment]
@webpro done :)

**Comment by webpro** [comment]
@jieverson What is actually different for Linux/Ubuntu *on Windows* from a dotfiles perspective? Does a Linux/Ubuntu-friendly dotfiles setup involve anything Windows-specific here?

**Comment by jieverson** [comment]
@webpro Actually there are some... on Windows, it always start from .bashrc... Also, I have examples of symlinking windows folders, and running windows programs from unix environment. I also have some examples of config files for making Cmder and Hyper.js (2 popular terminal emulators for Windows) run bash/zsh instead of cmd.

I also will keep updating this dotfiles with new stuff.

**Comment by webpro** [comment]
I think it's always `.bashrc` on Ubuntu 16. The Windows part is a bit confusing this way, and I'm not sure it will help people new(-ish) to dotfiles (the main target audience for this overview). I guess one can install any Ubuntu-friendly dotfiles, also on Windows. Last but not least, I'd like to see projects with a bit more support/community involved. That's why I'm closing this PR. Thanks again.

**Comment by jieverson** [comment]
Ok, I will accept your choice, but I just would like to point it out that sometimes unix community is closed minded to anything related to windows. People are still working out the limits of Bash on Ubuntu. And now there is not lots of places where we can find examples. I just thought this could be a good place to put it, 'cause I've used some of this dotfiles in the past, when deeping into unix, to learn lots of stuff (arch, osx, zsh, etc). But in windows I can't just get some Ubuntu or osx dotfiles (maybe part of them), cause for keeping it functional with OS without the need of windows shell I have to do some other stuff, like symlinking folders, create scripts for running windows programs, getting a better terminal emulator (cmd and powershell are crap), etc.

**Comment by strugee** [comment]
@jieverson I think the reason this PR was closed is that a lot of the things you've just listed aren't _really_ about dotfiles - they're about using Bash on Windows. @webpro isn't saying your resource isn't valuable, just that it doesn't fit in this particular list.

**Pull request closed without merging**
