### PR TITLE
Added dotty-cli to the list of macos tools

### PR DESCRIPTION
**Pull request by simskij**

### CODE REVIEW

**Comment by johnwyles** [comment]
*bump*

**Comment by webpro** [comment]
Hi, @simskij. Thanks for your PR. Personally, I'm not convinced of the added value of the tool you're submitting. What's the advantage of this versus using basically stow and a Brewfile?

**Comment by simskij** [comment]
To each their own I guess. :)

I made a tool that filled my own needs at the time while remaining a bit more maintainable (IMO) than a simple bash script.
- Running scripts
- Installing brew
- Installing application extensions (ie vscode, vim etc)
- Linking dotfiles

It’s still young though so I expect to simplify it further as well as adding additional nice to have functionality.

Just thought I might as well share, so feel free to take it or leave it basically :)

**Comment by webpro** [comment]
In general I think in this area it's good to stay closer to the bare metal, as opposed to add a layer of abstraction. The combination of what is behind this abstraction (linking dotfiles and Homebrew/Caskroom) is also a bit arbitrary. That's why I'm closing this PR.

**Pull request closed without merging**
