### PR TITLE
Adding johnwyles/bootstrap-macos to list of available dotfiles Bash and Zsh projects

### PR DESCRIPTION
**Pull request by johnwyles**

### CODE REVIEW

**Comment by webpro** [comment]
Sorry, but I can't merge a PR that has no description, and adds the same link at the top in three sections.

**Comment by johnwyles** [comment]
> Sorry, but I can't merge a PR that has no description

No description? The description is in the diff itself?
```Bootstrap for macOS (OS X / OSX) and Dotfiles | A simple `sh \| curl` installer setting up the Terminal, macOS settings, Applications, APIs, Programming languages, Shells (bash and zsh), etc.```

> and adds the same link at the top in three sections.
Then the sections need to be better organized?? This project does all of: ZSH + Bash + macOS so how would you propose this?

**Comment by webpro** [comment]
> No description? The description is in the diff itself?

I meant something like an introduction to your repo and why I should add it to this overview. I'm mainly looking for the added benefit for folks less experienced with dotfiles.

> Then the sections need to be better organized??

There are three sections of dotfiles repos (bash, zsh, fish), which has worked well so far. Suggestions to improve this are still welcome of course.

> This project does all of: ZSH + Bash + macOS so how would you propose this?

The "macOS" section is a subsection of "Tools". So it would be either the Bash or Zsh section I guess. But doing "all", combined with the fact that there is a lot going in the repo, in just two commits, that makes me hesitant to add this. It's hard for me to assess the overall quality (and no stars for the repo also doesn't help).

**Comment by johnwyles** [comment]
I will resubmit this later so we can leave it closed - do not hesitate about the 2 commits - I have squashed all the commits and force pushed - there have been near 100 commits probably by this point as I have refined it :)

**Pull request closed without merging**
