### PR TITLE
Add `dots2k`

### PR DESCRIPTION
**Pull request by 2KAbhishek**
I feel like dots2k has some value to add to this repo, main differentiation being support for different tools and platforms.

[dots2k](https://github.com/2kabhishek/dots2k)

Let me know what you think :)

### CODE REVIEW

**Comment by 2KAbhishek** [comment]
Hi @webpro, wanted to bring this to your attention, please let me know if any changes are needed

**Comment by webpro** [comment]
Nice! I can definitely see the efforts that went into this and can only appreciate it very much. It all seems very user and beginner friendly, awesome! ❤️

**Comment by webpro** [comment]
Btw, the https://2kabhishek.github.io/dots2k link at the bottom currently returns 404.

**Comment by 2KAbhishek** [comment]
Thanks for the heads up! I'll have to get my gh pages config fixed

**Pull request merged**
