### PR TITLE
Adding SaltStack dotfile repository and article

### PR DESCRIPTION
**Pull request by rawkode**
Signed-off-by: David McKay <david@rawkode.com>

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for your PR, @rawkode. I've scanned some content, and this actually summarizes the reason I'm not too eager to merge this PR:

> SaltStack makes software for complex systems management at scale.

I think SaltStack is kind of "scary" for people (relatively) new to dotfiles. Are there any more examples utilizing it other than your own dotfiles repo?

**Comment by rawkode** [comment]
SaltStack can be used for large complex infrastructures, sure. It's remarkably similar to Ansible in master-less mode and that's what I demonstrate in my dotfiles. Although i think I'm the only person doing it, i think its still a great example of utilising SaktStacks amazing feature set to build cross distribution dotfiles

**Comment by webpro** [comment]
I've added SaltStack to the list of tools

**Comment by rawkode** [comment]
I'm not really sure why my dotfiles aren't a good example of using SaltStack and can't be listed?

**Comment by webpro** [comment]
It's not about the quality of your dotfiles, it's about the goal of this overview in general: to guide people (relatively) new to dotfiles. I'll add your article next to the SaltStack tool, so people can still find your article/repo from this page.

**Pull request closed without merging**
