### PR TITLE
addind dotdrop - https://github.com/deadc0de6/dotdrop

### PR DESCRIPTION
**Pull request by deadc0de6**
Awesome list ! Adding dotdrop to it.
thanks !

### CODE REVIEW

**Comment by webpro** [comment]
Hi @deadc0de6, thanks for your PR. Your approach is interesting, so I'm wondering why it didn't gain much interest? I want to add projects to this page with some more support, so I can be more confident it's useful to a lot of people. That's why I'm closing this for now, but I'm happy to reconsider in the future.

**Comment by deadc0de6** [comment]
Hello, 
Too bad, the project is quite young I agree and thus it was the whole point of adding it to your list, bring more interest. 
Thanks anyway

**Comment by deadc0de6** [comment]
would you reconsider adding [dotdrop](https://github.com/deadc0de6/dotdrop) now that he gained more attention ?

**Comment by webpro** [comment]
Cool! Thanks for your patience :-) Please fix/open a new PR, as your fork has been deleted (I can't merge).

**Pull request closed without merging**
